#!/usr/bin/env bash
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx restart

